In [3]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json
from pprint import pprint
import us

In [7]:
url='https://api.openchargemap.io/v3/poi/?output=json&countrycode=US&maxresults=32000&compact=true'

In [8]:
charging_station_info = requests.get(url).json()

In [9]:
len(charging_station_info)

31227

In [10]:
with open('data.json', 'w') as f:
    json.dump(charging_station_info, f)

In [11]:
org_state_list=[]
for charging_station in charging_station_info:
    state_name=charging_station['AddressInfo']['StateOrProvince']
    if state_name !=None:
        org_state_list.append(state_name.upper())
        state_list=[x for x in org_state_list if len(x)==2]

In [12]:
state_dict = {i:state_list.count(i) for i in state_list}
print(len(state_dict))

52

In [134]:
state_dict
state_df=pd.DataFrame({"State":list(state_dict.keys()), "Number of Charging Stations":list(state_dict.values())})
state_df

   State  Number of Charging Stations
0     NY                         1328
1     CO                          868
2     ND                           42
3     CA                         7221
4     TX                         1536
5     PA                          631
6     VA                          727
7     AZ                          650
8     OR                          655
9     MO                          419
10    NJ                          451
11    NV                          346
12    KY                          173
13    SC                          379
14    TN                          537
15    WI                          303
16    VT                          199
17    NC                          947
18    LA                           98
19    FL                         1497
20    WA                          912
21    UT                          319
22    AR                          110
23    ID                           83
24    CT                          361
25    MA                          741
26    WY                           46
27    IL                          609
28    MT                           63
29    MD                          714
30    AK                           23
31    MN                          328
32    MI                          474
33    ME                          156
34    SD                           39
35    NH                          118
36    IA                          141
37    RI                          117
38    IN                          235
39    OH                          526
40    NE                           85
41    DE                           59
42    KS                          220
43    DC                          107
44    OK                          254
45    NM                           98
46    MS                           68
47    GA                          954
48    AL                          209
49    HI                          298
50    PR                            1
51    WV                           70

In [135]:
state_df['Number of Charging Stations']=state_df['Number of Charging Stations'].astype('int')
station_mean=state_df['Number of Charging Stations'].mean()
station_block=station_mean/3
station_median=state_df['Number of Charging Stations'].median()
station_median

300.5

In [136]:
list_sum=0
station_block_list=[]
for i in range (1,7):
    station_block_list.append(int(station_block*i))
    list_sum+=station_block_list[i-1]
    
station_block_list.append(max(state_df['Number of Charging Stations'])-list_sum+10)
station_block_list

[176, 353, 529, 706, 882, 1059, 3526]

In [137]:
column_name_list=['Number of Charging Stations 0 - 176','Number of Charging Stations 177 - 353', 'Number of Charging Stations  354 - 529', 'Number of Charging Stations 530 - 706', 'Number of Charging Stations 707 - 882', 'Number of Charging Stations 883 - 1059', 'Number of Charging Stations > 1059']
column_name_list

['Number of Charging Stations 0 - 176',
 'Number of Charging Stations 177 - 353',
 'Number of Charging Stations  354 - 529',
 'Number of Charging Stations 530 - 706',
 'Number of Charging Stations 707 - 882',
 'Number of Charging Stations 883 - 1059',
 'Number of Charging Stations > 1059']

In [138]:
for i, number in enumerate(station_block_list):
    state_df[f'{number}']=state_df.T.apply(lambda row:min(row.iloc[1]-(row.iloc[2:i+2]).sum(), number))
state_df=state_df.rename(columns={'176': column_name_list[0], '353': column_name_list[1], '529': column_name_list[2], '706': column_name_list[3], '882': column_name_list[4], '1059': column_name_list[5], '3526': column_name_list[6]})
state_df

,State,Number of Charging Stations,Number of Charging Stations 0 - 176,Number of Charging Stations 177 - 353,Number of Charging Stations 354 - 529,Number of Charging Stations 530 - 706,Number of Charging Stations 707 - 882,Number of Charging Stations 883 - 1059,Number of Charging Stations > 1059
0,NY,1328,176,353,529,270,0,0,0
1,CO,868,176,353,339,0,0,0,0
2,ND,42,42,0,0,0,0,0,0
3,CA,7221,176,353,529,706,882,1059,3516
4,TX,1536,176,353,529,478,0,0,0
5,PA,631,176,353,102,0,0,0,0
6,VA,727,176,353,198,0,0,0,0
7,AZ,650,176,353,121,0,0,0,0
8,OR,655,176,353,126,0,0,0,0
9,MO,419,176,243,0,0,0,0,0
10,NJ,451,176,275,0,0,0,0,0
11,NV,346,176,170,0,0,0,0,0
12,KY,173,173,0,0,0,0,0,0
13,SC,379,176,203,0,0,0,0,0
14,TN,537,176,353,8,0,0,0,0
15,WI,303,176,127,0,0,0,0,0
16,VT,199,176,23,0,0,0,0,0
17,NC,947,176,353,418,0,0,0,0
18,LA,98,98,0,0,0,0,0,0
19,FL,1497,176,353,529,439,0,0,0
20,WA,912,176,353,383,0,0,0,0
21,UT,319,176,143,0,0,0,0,0
22,AR,110,110,0,0,0,0,0,0
23,ID,83,83,0,0,0,0,0,0
24,CT,361,176,185,0,0,0,0,0
25,MA,741,176,353,212,0,0,0,0
26,WY,46,46,0,0,0,0,0,0
27,IL,609,176,353,80,0,0,0,0
28,MT,63,63,0,0,0,0,0,0
29,MD,714,176,353,185,0,0,0,0
30,AK,23,23,0,0,0,0,0,0
31,MN,328,176,152,0,0,0,0,0
32,MI,474,176,298,0,0,0,0,0
33,ME,156,156,0,0,0,0,0,0
34,SD,39,39,0,0,0,0,0,0
35,NH,118,118,0,0,0,0,0,0
36,IA,141,141,0,0,0,0,0,0
37,RI,117,117,0,0,0,0,0,0
38,IN,235,176,59,0,0,0,0,0
39,OH,526,176,350,0,0,0,0,0
40,NE,85,85,0,0,0,0,0,0
41,DE,59,59,0,0,0,0,0,0
42,KS,220,176,44,0,0,0,0,0
43,DC,107,107,0,0,0,0,0,0
44,OK,254,176,78,0,0,0,0,0
45,NM,98,98,0,0,0,0,0,0
46,MS,68,68,0,0,0,0,0,0
47,GA,954,176,353,425,0,0,0,0
48,AL,209,176,33,0,0,0,0,0
49,HI,298,176,122,0,0,0,0,0
50,PR,1,1,0,0,0,0,0,0
51,WV,70,70,0,0,0,0,0,0

In [139]:
state_df=state_df.drop(['Number of Charging Stations'], axis=1)
state_df

,State,Number of Charging Stations 0 - 176,Number of Charging Stations 177 - 353,Number of Charging Stations 354 - 529,Number of Charging Stations 530 - 706,Number of Charging Stations 707 - 882,Number of Charging Stations 883 - 1059,Number of Charging Stations > 1059
0,NY,176,353,529,270,0,0,0
1,CO,176,353,339,0,0,0,0
2,ND,42,0,0,0,0,0,0
3,CA,176,353,529,706,882,1059,3516
4,TX,176,353,529,478,0,0,0
5,PA,176,353,102,0,0,0,0
6,VA,176,353,198,0,0,0,0
7,AZ,176,353,121,0,0,0,0
8,OR,176,353,126,0,0,0,0
9,MO,176,243,0,0,0,0,0
10,NJ,176,275,0,0,0,0,0
11,NV,176,170,0,0,0,0,0
12,KY,173,0,0,0,0,0,0
13,SC,176,203,0,0,0,0,0
14,TN,176,353,8,0,0,0,0
15,WI,176,127,0,0,0,0,0
16,VT,176,23,0,0,0,0,0
17,NC,176,353,418,0,0,0,0
18,LA,98,0,0,0,0,0,0
19,FL,176,353,529,439,0,0,0
20,WA,176,353,383,0,0,0,0
21,UT,176,143,0,0,0,0,0
22,AR,110,0,0,0,0,0,0
23,ID,83,0,0,0,0,0,0
24,CT,176,185,0,0,0,0,0
25,MA,176,353,212,0,0,0,0
26,WY,46,0,0,0,0,0,0
27,IL,176,353,80,0,0,0,0
28,MT,63,0,0,0,0,0,0
29,MD,176,353,185,0,0,0,0
30,AK,23,0,0,0,0,0,0
31,MN,176,152,0,0,0,0,0
32,MI,176,298,0,0,0,0,0
33,ME,156,0,0,0,0,0,0
34,SD,39,0,0,0,0,0,0
35,NH,118,0,0,0,0,0,0
36,IA,141,0,0,0,0,0,0
37,RI,117,0,0,0,0,0,0
38,IN,176,59,0,0,0,0,0
39,OH,176,350,0,0,0,0,0
40,NE,85,0,0,0,0,0,0
41,DE,59,0,0,0,0,0,0
42,KS,176,44,0,0,0,0,0
43,DC,107,0,0,0,0,0,0
44,OK,176,78,0,0,0,0,0
45,NM,98,0,0,0,0,0,0
46,MS,68,0,0,0,0,0,0
47,GA,176,353,425,0,0,0,0
48,AL,176,33,0,0,0,0,0
49,HI,176,122,0,0,0,0,0
50,PR,1,0,0,0,0,0,0
51,WV,70,0,0,0,0,0,0

In [140]:
state_df.to_csv("station_state.csv",index=False)