In [1]:
# Import modules
import pandas as pd
import json
import pymongo

In [3]:
# Create a file path
files = "templates/incentives.csv"

In [4]:
# Read CSV File
unorganized = pd.read_csv(files)
unorganized

,State,Title,Description,Type
0,US,Clean Cities Coalition Network,The mission of Clean Cities Coalition Network ...,Programs
1,US,High Occupancy Vehicle (HOV) Lane Exemption,States are allowed to exempt certified alterna...,Laws and Regulations
2,US,Aftermarket Alternative Fuel Vehicle (AFV) Con...,Conventional original equipment manufacturer v...,Laws and Regulations
3,US,Qualified Plug-In Electric Vehicle (PEV) Tax C...,A tax credit is available for the purchase of ...,Incentives
4,AZ,Alternative Fuel Vehicle Emissions Test Exemption,"All-electric vehicles, hydrogen vehicles, and ...",State Incentives
...,...,...,...,...
277,NE,All-Electric Vehicle (EV) and Electric Vehicle...,Southern Public Power District (SPPD) offers r...,Utility/Private Incentives
278,CT,Plug-In Electric Vehicle (PEV) Deployment Goal,The Connecticut Department of Energy and Envir...,Laws and Regulations
279,DE,Plug-In Electric Vehicle (PEV) Charging Rate –...,Delmarva Power offers a time-of-use rate opti...,Utility/Private Incentives
280,CO,Electric Vehicle Supply Equipment (EVSE) Rebat...,SIEA offers residential customers a $500 rebat...,Utility/Private Incentives
281,CO,Electric Vehicle (EV) Rebate - San Isabel Elec...,SIEA residential customers a $500 rebate for t...,Utility/Private Incentives

In [5]:
# df=unorganized.groupby(['State'],as_index=False).agg(lambda x : x.sum() if x.dtype=='float64' else ','.join(x))

In [6]:
# Create a dataframe to count the type by state
total_count_df = unorganized.groupby(['State'],as_index=False)["Description"].count()
total_count_df = total_count_df.rename(columns={"Description": "Total_Type_Count"})
total_count_df.head()

  State  Total_Type_Count
0    AL                 1
1    AR                 2
2    AZ                11
3    CA                36
4    CO                11

In [7]:
# Create a dataframe grouped by state and type to show the count of each type
type_count_df = unorganized.groupby(['State','Type'])["Description"].nunique()
type_count_df = type_count_df.reset_index().rename(columns={"Type":"Type_Count_Name", "Description": "Type_Count"})
type_count_df.head()

  State             Type_Count_Name  Type_Count
0    AL        Laws and Regulations           1
1    AR        Laws and Regulations           2
2    AZ        Laws and Regulations           3
3    AZ            State Incentives           5
4    AZ  Utility/Private Incentives           3

In [8]:
# Add type name column and type count into a single column to add in json file

Specific_Count=[]
for index, row in type_count_df.iterrows():
    name = type_count_df["Type_Count_Name"][index]
    number = type_count_df["Type_Count"][index]
    Specific_Count.append(f"{name} : {number}")
    
# Specific_Count
    
type_count_df["Specific_Count"]=Specific_Count

type_count_df.drop(columns = ["Type_Count_Name", "Type_Count"], inplace=True)

type_count_df.head()

  State                  Specific_Count
0    AL        Laws and Regulations : 1
1    AR        Laws and Regulations : 2
2    AZ        Laws and Regulations : 3
3    AZ            State Incentives : 5
4    AZ  Utility/Private Incentives : 3

In [9]:
# Create a function to use on a groupby on strings
def join_and_remove_duplicates(x: list, sep: str) -> list:
    deduped = []
    for i in x:
        if i not in deduped:
            deduped.append(i)
    return sep.join(deduped)

In [10]:
# df=unorganized.groupby(['State'],as_index=False).agg(lambda x : x.sum() if x.dtype=='float64' else "|".join(set(x)))
# df.head(10)

In [11]:
# Group the states together to place in to json file for the description
specific_count_df=type_count_df.groupby(['State'],as_index=False).agg(lambda x : x.sum() if x.dtype=='float64' else join_and_remove_duplicates(x, "<br>"))
specific_count_df.head(10)

  State                                     Specific_Count
0    AL                           Laws and Regulations : 1
1    AR                           Laws and Regulations : 2
2    AZ  Laws and Regulations : 3<br>State Incentives :...
3    CA  Laws and Regulations : 9<br>State Incentives :...
4    CO  Laws and Regulations : 4<br>State Incentives :...
5    CT  Laws and Regulations : 2<br>State Incentives :...
6    DC   Laws and Regulations : 1<br>State Incentives : 2
7    DE  Laws and Regulations : 1<br>State Incentives :...
8    FL  Laws and Regulations : 2<br>Utility/Private In...
9    GA  Laws and Regulations : 1<br>State Incentives :...

In [12]:
# Group the csv file by the state
df=unorganized.groupby(['State'],as_index=False).agg(lambda x : x.sum() if x.dtype=='float64' else join_and_remove_duplicates(x, "<hr>"))
df.head(10)

,State,Title,Description,Type
0,AL,Plug-In Electric Vehicle (PEV) Fee,"Effective January 1, 2020, PEV owners must pay...",Laws and Regulations
1,AR,Alternative Fuel Vehicle Conversion Notificati...,Any individual or company who converts a vehic...,Laws and Regulations
2,AZ,Alternative Fuel Vehicle Emissions Test Exempt...,"All-electric vehicles, hydrogen vehicles, and ...",State Incentives<hr>Laws and Regulations<hr>Ut...
3,CA,Plug-In Electric Vehicle (PEV) Charging Rate R...,The Sacramento Municipal Utility District (SMU...,Utility/Private Incentives<hr>State Incentives...
4,CO,Alternative Fuel Vehicle (AFV) Weight Exemptio...,Gross vehicle weight rating limits for AFVs ar...,State Incentives<hr>Laws and Regulations<hr>Ut...
5,CT,Reduced Registration Fee for Electric Vehicles...,EVs are eligible for a reduced biennial vehicl...,State Incentives<hr>Utility/Private Incentives...
6,DC,Plug-In Electric Vehicle (PEV) Title Excise Ta...,Qualified PEVs are exempt from the excise tax ...,State Incentives<hr>Laws and Regulations
7,DE,Vehicle-to-Grid Energy Credit<hr>Alternative F...,Retail electricity customers with at least one...,State Incentives<hr>Utility/Private Incentives...
8,FL,Electric Vehicle (EV) Insurance Regulation<hr>...,Insurance companies may not impose surcharges ...,Laws and Regulations<hr>Utility/Private Incent...
9,GA,High Occupancy Vehicle (HOV) and High Occupanc...,Alternative fuel vehicles (AFVs) displaying th...,State Incentives<hr>Utility/Private Incentives...

In [13]:
# Create a list of states in abbreviation
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

In [14]:
# Create the list by full name
fullname = ['Alabama','Alaska','Arizona','Arkansas',
    'California','Colorado','Connecticut','Delaware',
    'District of Columbia','Florida','Georgia','Hawaii',
    'Idaho','Illinois','Indiana','Iowa','Kansas',
    'Kentucky','Louisiana','Maine','Maryland',
    'Massachusetts','Michigan','Minnesota','Mississippi',
    'Missouri','Montana','Nebraska','Nevada',
    'New Hampshire','New Jersey','New Mexico','New York',
    'North Carolina','North Dakota','Ohio','Oklahoma',
    'Oregon','Pennsylvania','Rhode Island','South Carolina',
    'South Dakota','Tennessee','Texas','Utah',
    'Vermont','Virginia','Washington','West Virginia',
    'Wisconsin','Wyoming']

In [15]:
# Make the list in dataframe
us_state_abbrev = pd.DataFrame({"State": states, "Full_Name": fullname})
us_state_abbrev.head()

  State   Full_Name
0    AL     Alabama
1    AK      Alaska
2    AZ     Arizona
3    AR    Arkansas
4    CA  California

In [16]:
# Merge the data frames to add full names of the state
new_incentive_df = pd.merge(left=df, right=us_state_abbrev, on="State")
new_incentive_df.head()

,State,Title,Description,Type,Full_Name
0,AL,Plug-In Electric Vehicle (PEV) Fee,"Effective January 1, 2020, PEV owners must pay...",Laws and Regulations,Alabama
1,AR,Alternative Fuel Vehicle Conversion Notificati...,Any individual or company who converts a vehic...,Laws and Regulations,Arkansas
2,AZ,Alternative Fuel Vehicle Emissions Test Exempt...,"All-electric vehicles, hydrogen vehicles, and ...",State Incentives<hr>Laws and Regulations<hr>Ut...,Arizona
3,CA,Plug-In Electric Vehicle (PEV) Charging Rate R...,The Sacramento Municipal Utility District (SMU...,Utility/Private Incentives<hr>State Incentives...,California
4,CO,Alternative Fuel Vehicle (AFV) Weight Exemptio...,Gross vehicle weight rating limits for AFVs ar...,State Incentives<hr>Laws and Regulations<hr>Ut...,Colorado

In [17]:
# Merge the data frames togegher to get the count
new_incentive_df = pd.merge(left=new_incentive_df, right=total_count_df, on="State")
new_incentive_df.head()

,State,Title,Description,Type,Full_Name,Total_Type_Count
0,AL,Plug-In Electric Vehicle (PEV) Fee,"Effective January 1, 2020, PEV owners must pay...",Laws and Regulations,Alabama,1
1,AR,Alternative Fuel Vehicle Conversion Notificati...,Any individual or company who converts a vehic...,Laws and Regulations,Arkansas,2
2,AZ,Alternative Fuel Vehicle Emissions Test Exempt...,"All-electric vehicles, hydrogen vehicles, and ...",State Incentives<hr>Laws and Regulations<hr>Ut...,Arizona,11
3,CA,Plug-In Electric Vehicle (PEV) Charging Rate R...,The Sacramento Municipal Utility District (SMU...,Utility/Private Incentives<hr>State Incentives...,California,36
4,CO,Alternative Fuel Vehicle (AFV) Weight Exemptio...,Gross vehicle weight rating limits for AFVs ar...,State Incentives<hr>Laws and Regulations<hr>Ut...,Colorado,11

In [18]:
# Merge the dataframe for the description
new_incentive_df = pd.merge(left=new_incentive_df, right=specific_count_df, on="State")
new_incentive_df.head()

,State,Title,Description,Type,Full_Name,Total_Type_Count,Specific_Count
0,AL,Plug-In Electric Vehicle (PEV) Fee,"Effective January 1, 2020, PEV owners must pay...",Laws and Regulations,Alabama,1,Laws and Regulations : 1
1,AR,Alternative Fuel Vehicle Conversion Notificati...,Any individual or company who converts a vehic...,Laws and Regulations,Arkansas,2,Laws and Regulations : 2
2,AZ,Alternative Fuel Vehicle Emissions Test Exempt...,"All-electric vehicles, hydrogen vehicles, and ...",State Incentives<hr>Laws and Regulations<hr>Ut...,Arizona,11,Laws and Regulations : 3<br>State Incentives :...
3,CA,Plug-In Electric Vehicle (PEV) Charging Rate R...,The Sacramento Municipal Utility District (SMU...,Utility/Private Incentives<hr>State Incentives...,California,36,Laws and Regulations : 9<br>State Incentives :...
4,CO,Alternative Fuel Vehicle (AFV) Weight Exemptio...,Gross vehicle weight rating limits for AFVs ar...,State Incentives<hr>Laws and Regulations<hr>Ut...,Colorado,11,Laws and Regulations : 4<br>State Incentives :...

In [21]:
# Open json file
with open("templates/us.json", "r") as read_file:
    data = json.load(read_file)

In [22]:
# Read specific block in json 
z=data['features']
# z[0]['properties']

In [23]:
# Add blocks into Json file
for info in z:
    for index,each in new_incentive_df.iterrows():
#         print(each["Full_Name"])
        if info['properties']["name"] == each["Full_Name"]:
            info['properties'].update({"Incentive_Title": each["Title"]})
            info['properties'].update({"Incentive_Description": each["Description"]})
            info['properties'].update({"Incentive_Type": each["Type"]})
            info['properties'].update({"Total_Type_Count": each["Total_Type_Count"]})
            info['properties'].update({"Specific_Count": each["Specific_Count"]})

In [24]:
data['features'] = z

In [26]:
# Write in the json file
with open('templates/refinedData.json', 'w') as outfile:
    json.dump(data, outfile)